global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'curl-metrics'
    static_configs:
      - targets: ['172.17.0.1:9100']

  - job_name: 'python-exporter'
    static_configs:
      - targets: ['172.17.0.1:8000']  # if you're using Docker Desktop

